### ISSUE TITLE
Issue with MSBTLoot : line 83

### ISSUE THREAD

**Issue by acuD1** [artscout/MikScrollingBattleText#3]
Hi looks like an issue with currency drop when out of combat !

![error](https://user-images.githubusercontent.com/43761367/119137668-59f80880-ba41-11eb-8a90-c7500e7114ae.png)

**Comment by acuD1** [comment]
Edit : It's from honor gain

**Comment by artscout** [comment]
Oh, thanks a lot, couldn't catch that before, now I know what to look for, thanks again. 
Also pleae keep in mind that while I'm good programmer - I've never developed for Wow with Lua before so it might take some time for me to work out bugs. Well that or original authors might wake up and fix that for good )

**Comment by artscout** [comment]
Erm. Are you sure that you have correct addon installed? I can't catch this error on BattleGrounds at all and string numbers are all wrong...

**Comment by Clvd0x** [comment]
> 
> 
> Erm. Are you sure that you have correct addon installed? I can't catch this error on BattleGrounds at all and string numbers are all wrong...

Im facing the same issue. Do you have "Honor Gains" enabled? It is under Events -> Event Category[Notification] -> Honor Gains.

**Comment by artscout** [comment]
1. I'm not sure that it moved there. I think that move happened much later and it should be left as it is in TBC. Otherwise it couldn't work at all with anything really. But I will look into this too.
2. Yep, but like above - it works with other things

**Comment by artscout** [comment]
1 yes it was moved on 9.0.1, I pretty much doubt that TBC based on this.

**Comment by artscout** [comment]
But I will test that anyway. Who knows )

**Comment by artscout** [comment]
Ah I'm stupid. Of course this won't be called with anything else, the only currency we have is Honor points currently, so it would be called only in that case. I guess now we have to see if this change came to TBC, though I still didn't get any error with it previously, while playing in BG.

**Comment by artscout** [comment]
BTW: /script print(C_CurrencyInfo.GetCurrencyInfo(1901).quantity) - yep, you were right about function change. Loool.

**Comment by artscout** [comment]
Ok, it's somewhat bad news - I've looked up on what comes from parserEvent and itemLink that comes through there when Honor points arrives are clearly broken, as it's not am itemLink anymore, I just receive amount without anything else. I think that it has something to do with combat logs, but not sure. WIll investigate more

**Comment by artscout** [comment]
Alright I fixed that. Problem was that Honor points are coming to combat messages without itemLink, so I've made a filter for such messages and add code to get info from honor points item id (1901), so that's how it work now. If anyone has better ideas I'm all ears.
