### ISSUE TITLE
Testing the WOLTKC druid heal

### ISSUE THREAD

**Issue by Maqos147** [artscout/MikScrollingBattleText#5]
During my testing I did not get any lua errors configured with Elvui. The healing text only shows when it is a cast one for example healing touch or regrowth but only the start then the periodic heals stop showing. 
[https://postimg.cc/V5Hfs9R5](url)

**Comment by artscout** [comment]
At the picture you have full HP. So it won't be showing ticks that are doing nothing. Blizzard battle text showing ticks no matter what and that's the difference

**Comment by artscout** [comment]
JFYI: I've tested on druid and priest with different kind of HoT's and everything works as it should
