### ISSUE TITLE
Update for 3.4.1 Ulduar Phase2 new patch?

### ISSUE THREAD

**Issue by Pocokk** [artscout/MikScrollingBattleText#8]
Dear artscout,

Any chance that you might be able to make adjustments to the addon so that it is still working properly with the newest TOC update and such?

Thank you!

**Comment by pimbeenes** [comment]
Try it again, mine magically started working again.

**Comment by pimbeenes** [comment]
Mine was broken too, but it started working again without updating it. It's possible that it was caused by another addon.

**Comment by RazorsEdge88** [comment]
![image](https://user-images.githubusercontent.com/71830790/213903921-54a50626-22a7-46af-938a-7eb621ba2812.png)
mine is working, but is making unlimited errors with RClootcounsil it seems

**Comment by artscout** [comment]
Working on it

**Comment by Pocokk** [comment]
Thank you for the quick fix/upate!

**Comment by Pocokk** [comment]
Seems to work properly, thank you once again!
